### PR TITLE
take CSP out of report only mode (bug 1126844)

### PR DESCRIPTION
**Pull request by andymckay**

### CODE REVIEW

**Comment by kumar303** [comment]
looks like a legit test failure

**Comment by kumar303** [comment]
I am nervous about this because things might not work when CSP is enforced but, hey :/ We can always roll back.

r+ after test fix

**Comment by andymckay** [comment]
ha didn't think that would be tested :)

**Comment by amuntner** [comment]
Heard back from Joe Stevenson, he says to keep the same reporting endpoint.

**Pull request merged**
