### PR TITLE
Remove compression + CSS (bug 1135205)

### PR DESCRIPTION
**Pull request by muffinresearch**
* Removes compress_assets from fabfile
* Removes settings relating to jinjo minification
* Removes package.json
* Removes uitests settings (uitests are already history)
* Remove CSS.

Depends on #603

r? @kumar303 

r? @jason for the fabfile changes. Also do we still need this? https://github.com/mozilla/webpay/tree/master/scripts/update (I can nuke it as part of this if you don't need it any more).

### CODE REVIEW

**Comment by muffinresearch** [comment]
As I suspected tests are going to fail until #603 lands.

**Comment by kumar303** [comment]
looks good to me.

r+

**Comment by muffinresearch** [comment]
0ops left in a css() call in the base template.

**Comment by jasonthomas** [comment]
fabfile changes lgtm. https://github.com/mozilla/webpay/tree/master/scripts/update is no longer used and can be removed.
r+

**Pull request merged**
